baseURL: /
languageCode: en-us
title: Headlamp
theme: kinvolk
assetsDir: assets
params:
  description: Headlamp is an easy to use and extensible Kubernetes web UI
  docs:
    github_edit_url: https://github.com/kinvolk/headlamp/edit/main/docs/
    issues_url: https://github.com/kinvolk/headlamp/issues/new?labels=kind/docs
    external_docs:
    - repo: https://github.com/kinvolk/headlamp.git
      name: "latest"
      branch: "main"
      dir: "docs"

menu:
  main:
    - name: Blog
      url: /blog
      identifier: blog
      weight: -500
    - name: Docs
      url: /docs
      identifier: docs
      weight: -200
