baseURL: /
languageCode: en-us
title: Headlamp
theme: kinvolk-generic
assetsDir: assets
copyright: Microsoft Inc. All Rights Reserved.
params:
  description: Headlamp is an easy to use and extensible Kubernetes web UI
  favicon: "favicon.png"
  social:
    - title: twitter
      url: 'https://twitter.com/headlamp_ui'
      image: 'twitter-icon'
    - title: github
      url: 'https://github.com/kinvolk/headlamp'
      image: 'github-icon'
  docs:
    github_edit_url: https://github.com/kinvolk/headlamp/edit/main/docs/
    issues_url: https://github.com/kinvolk/headlamp/issues/new?labels=kind/docs
    external_docs:
    - repo: https://github.com/kinvolk/headlamp.git
      name: "latest"
      branch: "main"
      dir: "docs"

menu:
  main:
    - name: Blog
      url: /blog
      identifier: blog
      weight: -500
    - name: Install
      url: /docs/latest/installation/
      identifier: install
      weight: -100
    - name: Github
      url: https://github.com/kinvolk/inspektor-gadget
      identifier: github
      weight: -50
      pre: github
    - name: Docs
      url: /docs
      identifier: docs
      weight: -30